export default {
   // Light theme colors
   light: {
      yellow_light: "#FFE478",
      blue_light: "#85C1E9",
      red_light: "#EA9D9D",
      green_light: "#5CB85C",
      food_category_light: "#7D9D72",
      housing_category_light: "#E4B363",
      entertainment_category_light: "#4D96FF",
      transport_category_light: "#B8405E",
      education_category_light: "#A288E3",
      healthcare_category_light: "#8EC6B7",
      shopping_category_light: "#F4A7B9",
      other_category_light: "#A1A1A1",
      frame_stroke_light: "#D6D6D6",
      input_text_light: "#777777",
      frame_fill_light: "#D6D6D6",
      page_background_light: "#FFFFFF",
      card_text_light: "#333333",
      percentage_background_light: "#FFFFFF",
      dot_background_light: "#D6D6D6",
      card_title_light: "#333333",
      card_description_light: "#777777",
      text_input_background_light: "#FFFFFF",
   },
   // Dark theme colors
   dark: {
      yellow_dark: "#F39C12",
      blue_dark: "#4DB8F0",
      red_dark: "#EF6464",
      green_dark: "#2ECC71",
      food_category_dark: "#4A7C59",
      housing_category_dark: "#B9832B",
      entertainment_category_dark: "#3D75C6",
      transport_category_dark: "#921C39",
      education_category_dark: "#7139FE",
      healthcare_category_dark: "#4DA08A",
      shopping_category_dark: "#CB4665",
      other_category_dark: "#5F5F5F",
      frame_stroke_dark: "#7C7C7C",
      input_text_dark: "#777777",
      frame_fill_dark: "#1F1F1F",
      page_background_dark: "#1F1F1F",
      card_text_dark: "#333333",
      percentage_background_dark: "#FFFFFF",
      dot_background_dark: "#D6D6D6",
      card_title_dark: "#DCDCDC",
      card_description_dark: "#E5E5E5",
      text_input_background_dark: "#2D2D2D",
   },
};
